// React/reactjs-in-action-main/react-basics/src/change-detection/ChangeDetection.tsx
import './ChangeDetection.css';
import {useState} from "react";

function ChangeDetection() {
    // let title = "Let's learn about change detection!";
    const [title, setTitle] =
        useState("Let's learn about change detection!");
    // let x = 0;
    const [x, setX]
        = useState(2);

    function handleClick() {
        setTitle('Hey look, I changed!');
        alert(title);
    }

    function increment() {
        // setX(x + 1);
        // setX(x * 2);
        setX(x => {
            x++;
            x *= 2;
            return x;
        });
    }

    function decrement() {
        setX(x => {
            x /= 2;
            x--;
            return x;
        });
    }

    return (
        <>
            <h3>{title}</h3>
            <button onClick={handleClick}>Click Me</button>
            <h3>X={x}</h3>
            <button onClick={increment}>+ INC</button>
            <button onClick={decrement}>+ DEC</button>
        </>
    );
}

export default ChangeDetection;

// Angular/angular-in-action-main/angular-basics/src/app/change-detection/change-detection.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-change-detection',
  template: `
    <h3>{{ title }}</h3>
    <button (click)="handleClick()">
      Click Me
    </button>
    <h3>X={{ x }}</h3>
    <button (click)="increment()">+ INC</button>
    <button (click)="decrement()">- DEC</button>
  `,
  styleUrl: './change-detection.component.scss'
})
export class ChangeDetectionComponent {
  title = "Let's learn about change detection";
  x = 1;

  handleClick(){
    this.title = "Hey look!, I changed."
  }

  increment(){
    this.x++;
    this.x *= 2;
  }

  decrement(){
    this.x /= 2;
    this.x--;
  }
}
